### ISSUE TITLE
doesn't compile on Debian9 with go1.7.4 / go minimum version

### ISSUE THREAD

**Issue by kiuuik** [arsham/blush#6]
I have Debian 9 Stretch and go get doesn't work

```
$ go version
go version go1.7.4 linux/amd64

$ go get github.com/arsham/blush
# github.com/arsham/blush/cmd
opt/go/src/github.com/arsham/blush/cmd/args.go:78: undefined: sort.SliceStable
opt/go/src/github.com/arsham/blush/cmd/args.go:118: undefined: sort.SliceStable
opt/go/src/github.com/arsham/blush/cmd/args.go:122: undefined: sort.SliceStable
```

SliceStable seems to be introduced with 1.8, https://golang.org/doc/go1.8 ? So maybe the readme needs an update?

**Comment by arsham** [comment]
Thank you for reporting. You are absolutely right, it requires go>=1.8. I will update the readme. There is a linux binary under [release](https://github.com/arsham/blush/releases) section. 

Is it possible to upgrade go for debian 9? If not I will look into possible solutions for supporting go 1.7.

**Comment by kiuuik** [comment]
More recent version of go seem to be available in the [backports repo](https://packages.debian.org/stretch-backports/golang) in Debian 9. 

Even if they weren't: There's the binary you share and probably all people who run Debian can use a virtual machine if they really want to compile themselves - I guess many people would prefer addtional features over compatibility to some old machines ? 

Thanks for your time and great software!

**Comment by arsham** [comment]
The binary should work without go tool. However I will look into supporting old versions. `SliceStable` is just a convenience, if I managed to sort the built constraints out I will make two versions, otherwise I can change the sort function.

Thanks for showing interest in this app!

**Comment by arsham** [comment]
It now supports go 1.7. Please try again and let me know if you have any issues. 

Cheers!

**Comment by kiuuik** [comment]
Thanks for the very quick fix! Now it compiles without complaining and a test search delivered the expected results. So it seems to work for me.
